### ISSUE TITLE
idea maybe for file dedup?

### ISSUE THREAD

**Issue by yawnt** [io12/nix-flatpak#1]
hi!
this project looks great :)

based on your other comments in the nixpkgs issue, i was wondering whether you had tried using https://git.sr.ht/~jack/nix-freeze-tree to solve the issue of deduplication (ie: moving from ostree store to /nix/store)

i'm not an expert in nix by any stretch of the imagination but i was wondering something like 

derivation that takes ostree runtime and extract it to a folder -> run derivation through lib.freeze -> now you have a derivation which has all single files stored in /nix/store

**Comment by io12** [comment]
> based on your other comments in the nixpkgs issue, i was wondering whether you had tried using https://git.sr.ht/~jack/nix-freeze-tree to solve the issue of deduplication (ie: moving from ostree store to /nix/store)

> derivation that takes ostree runtime and extract it to a folder -> run derivation through lib.freeze -> now you have a derivation which has all single files stored in /nix/store

It looks like nix-freeze-tree uses symlinks, so files in the flatpak runtime will have symlinks to files in /nix/store. I originally didn't think something with symlinks was a good idea because flatpaks run inside a sandbox that doesn't necessarily have access to /nix/store, so all the symlinks would be broken. Maybe exposing /nix/store to the sandbox and using symlinks could work though. Thanks!
